//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 03:32:31 PM BST 
//


package org.openworm.simulationengine.model.sph;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openworm.simulationengine.model.sph package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SphModelRoot_QNAME = new QName("http://www.example.org/SPHSchema", "sphModelRoot");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openworm.simulationengine.model.sph
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPHModel }
     * 
     */
    public SPHModel createSPHModel() {
        return new SPHModel();
    }

    /**
     * Create an instance of {@link SPHCell }
     * 
     */
    public SPHCell createSPHCell() {
        return new SPHCell();
    }

    /**
     * Create an instance of {@link Vector3D }
     * 
     */
    public Vector3D createVector3D() {
        return new Vector3D();
    }

    /**
     * Create an instance of {@link SPHParticle }
     * 
     */
    public SPHParticle createSPHParticle() {
        return new SPHParticle();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPHModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/SPHSchema", name = "sphModelRoot")
    public JAXBElement<SPHModel> createSphModelRoot(SPHModel value) {
        return new JAXBElement<SPHModel>(_SphModelRoot_QNAME, SPHModel.class, null, value);
    }

}
