//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.16 at 02:08:39 PM IST 
//


package org.openworm.simulationengine.model.sph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPHParticle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPHParticle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="positionVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="velocityVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="velocityEvaluationVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="viscosityForceVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="gravityForceVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="pressureForceVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="normalVector" type="{http://www.example.org/SPHSchema}Vector3D"/>
 *         &lt;element name="neighbourIndexes" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mass" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="viscosity" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="density" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPHParticle", propOrder = {
    "positionVector",
    "velocityVector",
    "velocityEvaluationVector",
    "viscosityForceVector",
    "gravityForceVector",
    "pressureForceVector",
    "normalVector",
    "neighbourIndexes"
})
public class SPHParticle {

    @XmlElement(required = true)
    protected Vector3D positionVector;
    @XmlElement(required = true)
    protected Vector3D velocityVector;
    @XmlElement(required = true)
    protected Vector3D velocityEvaluationVector;
    @XmlElement(required = true)
    protected Vector3D viscosityForceVector;
    @XmlElement(required = true)
    protected Vector3D gravityForceVector;
    @XmlElement(required = true)
    protected Vector3D pressureForceVector;
    @XmlElement(required = true)
    protected Vector3D normalVector;
    @XmlElement(type = Integer.class)
    protected List<Integer> neighbourIndexes;
    @XmlAttribute(name = "mass")
    protected Float mass;
    @XmlAttribute(name = "viscosity")
    protected Float viscosity;
    @XmlAttribute(name = "density")
    protected Float density;
    @XmlAttribute(name = "pressure")
    protected Float pressure;

    /**
     * Gets the value of the positionVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getPositionVector() {
        return positionVector;
    }

    /**
     * Sets the value of the positionVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setPositionVector(Vector3D value) {
        this.positionVector = value;
    }

    /**
     * Gets the value of the velocityVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getVelocityVector() {
        return velocityVector;
    }

    /**
     * Sets the value of the velocityVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setVelocityVector(Vector3D value) {
        this.velocityVector = value;
    }

    /**
     * Gets the value of the velocityEvaluationVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getVelocityEvaluationVector() {
        return velocityEvaluationVector;
    }

    /**
     * Sets the value of the velocityEvaluationVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setVelocityEvaluationVector(Vector3D value) {
        this.velocityEvaluationVector = value;
    }

    /**
     * Gets the value of the viscosityForceVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getViscosityForceVector() {
        return viscosityForceVector;
    }

    /**
     * Sets the value of the viscosityForceVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setViscosityForceVector(Vector3D value) {
        this.viscosityForceVector = value;
    }

    /**
     * Gets the value of the gravityForceVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getGravityForceVector() {
        return gravityForceVector;
    }

    /**
     * Sets the value of the gravityForceVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setGravityForceVector(Vector3D value) {
        this.gravityForceVector = value;
    }

    /**
     * Gets the value of the pressureForceVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getPressureForceVector() {
        return pressureForceVector;
    }

    /**
     * Sets the value of the pressureForceVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setPressureForceVector(Vector3D value) {
        this.pressureForceVector = value;
    }

    /**
     * Gets the value of the normalVector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3D }
     *     
     */
    public Vector3D getNormalVector() {
        return normalVector;
    }

    /**
     * Sets the value of the normalVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3D }
     *     
     */
    public void setNormalVector(Vector3D value) {
        this.normalVector = value;
    }

    /**
     * Gets the value of the neighbourIndexes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neighbourIndexes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeighbourIndexes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getNeighbourIndexes() {
        if (neighbourIndexes == null) {
            neighbourIndexes = new ArrayList<Integer>();
        }
        return this.neighbourIndexes;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMass(Float value) {
        this.mass = value;
    }

    /**
     * Gets the value of the viscosity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getViscosity() {
        return viscosity;
    }

    /**
     * Sets the value of the viscosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setViscosity(Float value) {
        this.viscosity = value;
    }

    /**
     * Gets the value of the density property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDensity() {
        return density;
    }

    /**
     * Sets the value of the density property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDensity(Float value) {
        this.density = value;
    }

    /**
     * Gets the value of the pressure property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPressure() {
        return pressure;
    }

    /**
     * Sets the value of the pressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPressure(Float value) {
        this.pressure = value;
    }

}
